const ADDENDUM_UNITS = {
  space_marines: [
    { id:'sm_eradicators', stats:['5"','3+','3+','4','4','2','2','8','3+'], name:'Eradicators', role:'Elites', pts:35, isNew:true, wargear:['Multi-melta','Bolt Pistol','Total Obliteration'] },
    { id:'sm_brutalis', stats:['8"','2+','3+','8','10','12','5','9','2+'], name:'Brutalis Dreadnought', role:'Elites', pts:175, isNew:true, wargear:['Brutalis Fists','Twin Bolt Rifles','Ferocious Charge'] },
    { id:'sm_ballistus', stats:['6"','4+','2+','8','10','12','3','9','2+'], name:'Ballistus Dreadnought', role:'Heavy Support', pts:155, isNew:true, wargear:['Lascannon','Twin Fragstorm Launcher','Targeting Protocols'] },
    { id:'sm_infernus', stats:['6"','3+','3+','4','4','2','2','8','3+'], name:'Infernus Marines', role:'Elites', pts:22, isNew:true, wargear:['Pyreblaster','Bolt Pistol','Wall of Flame'] },
    { id:'sm_judiciar', stats:['6"','2+','3+','4','4','5','4','9','3+'], name:'Judiciar', role:'Elites', pts:80, isNew:true, wargear:['Tempormortis','Bolt Pistol','3+ Invulnerable','Death Knell'] },
    { id:'sm_apoth_biologis', stats:['6"','3+','3+','4','4','4','3','9','3+'], name:'Apothecary Biologis', role:'Elites', pts:65, isNew:true, wargear:['Absolvor Bolt Pistol','Narthecium','Biological Expertise'] },
    { id:'sm_company_heroes', stats:['6"','3+','3+','4','4','2','2','9','3+'], name:'Company Heroes', role:'Elites', pts:75, isNew:true, wargear:['Relic Blade','Company Banner','Bolt Rifles','Honour of Chapter'] },
    { id:'sm_lt_titus', stats:['6"','2+','2+','4','4','5','5','9','3+'], name:'Lieutenant Titus (Ultramarines)', role:'HQ', pts:95, isNew:true, wargear:['Might of Ultramar','Master-crafted Bolter','3+ Invulnerable'] },
  ],
  blood_angels: [
    { id:'ba_dc_brutalis', stats:['8"','2+','3+','8','10','12','5','9','2+'], name:'Death Company Brutalis Dreadnought', role:'Elites', pts:185, isNew:true, wargear:['Brutalis Fists','Twin Bolt Rifles','Black Rage','Red Thirst'] },
  ],
  dark_angels: [
    { id:'da_lion', stats:['7"','2+','2+','6','6','14','6','10','2+'], name:"Lion El'Jonson, Primarch", role:'Lord of War', pts:350, isNew:true, wargear:['The Lion Sword','Wolf Blade','4+ Invulnerable','Lord of the First'] },
  ],
  chaos_space_marines: [
    { id:'csm_vashtorr', stats:['12"','2+','2+','7','7','14','6','10','3+'], name:'Vashtorr the Arkifane', role:'Lord of War', pts:380, isNew:true, wargear:['The Soul Shrive',"Arkifane's Claw",'Daemonforge Blast','4+ Invulnerable'] },
    { id:'csm_acc_cultists', stats:['6"','3+','5+','4','4','2','3','7','5+'], name:'Accursed Cultists', role:'Troops', pts:12, isNew:true, wargear:['Cursed Weapons','Autopistol','Mutant Resilience'] },
    { id:'csm_dark_commune', stats:['6"','3+','3+','3','3','3','2','8','5+'], name:'Dark Commune', role:'HQ', pts:55, isNew:true, wargear:["Demagogue's Staff",'Crude Weapons','Unholy Invocations'] },
  ],
  thousand_sons: [
    { id:'ts_infernal_master', stats:['6"','3+','3+','3','3','4','3','9','3+'], name:'Infernal Master', role:'HQ', pts:90, isNew:true, wargear:['Force Stave','Bolt Pistol','Malefic Pacts','Mastery Level 1'] },
  ],
  death_guard: [
    { id:'dg_miasmic', stats:['-','-','-','-','8','8','-','-','3+'], name:'Miasmic Malignifier', role:'Fortification', pts:75, isNew:true, wargear:['Putrid Miasma','Diseased Structure','Explodes'] },
  ],
  chaos_daemons: [
    { id:'cd_belakor_updated', stats:['14"','2+','2+','8','8','18','7','10','4+'], name:"Be'lakor, The Dark Master (updated)", role:'Lord of War', pts:410, isNew:true, wargear:['Blade of Shadows','Daemonic Claws','Shadow Form','Mastery Level 2'] },
  ],
  eldar: [
    { id:'el_illic', stats:['7"','2+','2+','3','3','4','4','9','5+'], name:'Illic Nightspear', role:'HQ', pts:100, isNew:true, wargear:['Voidbringer','Appear Unbidden','Ancient Hunter'] },
    { id:'el_baharroth', stats:['14"','2+','2+','3','3','5','5','9','4+'], name:'Baharroth, Cry of the Wind', role:'HQ', pts:120, isNew:true, wargear:['Swiftstrike','Lasblaster','Grenade Pack','Phoenix Lord 4+'] },
    { id:'el_fuegan', stats:['7"','2+','2+','4','4','6','5','9','3+'], name:'Fuegan, The Burning Lance', role:'HQ', pts:165, isNew:true, wargear:['The Fire Axe','Firepike','The Burning','Phoenix Lord 4+'] },
    { id:'el_autarch_way', stats:['12"','2+','2+','3','3','5','4','9','3+'], name:'Autarch Wayleaper', role:'HQ', pts:100, isNew:true, wargear:['Blade of Anaris','Reaper Launcher','Path of Command','4+ Invulnerable'] },
    { id:'el_hemlock', stats:['20-60"','6+','3+','6','6','8','1','9','3+'], name:'Hemlock Wraithfighter', role:'Flyer', pts:190, isNew:true, wargear:['Twin Heavy D-scythes','Spirit Stones','Mindshock'] },
    { id:'el_shroud_runners', stats:['16"','3+','3+','3','4','2','2','8','4+'], name:'Shroud Runners', role:'Fast Attack', pts:35, isNew:true, wargear:['Ranger Long Rifle','Jetbike Cannon','Scouts','Outflank'] },
    { id:'el_lhykhis', stats:['7"','2+','2+','3','3','5','5','9','3+'], name:'Lhykhis, Warp Spider Exarch', role:'Elites', pts:110, isNew:true, wargear:['Twin Death Spinner','Powerblades','Warp Jump','4+ Invulnerable'] },
    { id:'el_irillyth', stats:['12"','2+','2+','3','3','6','4','9','4+'], name:'Irillyth, Shade of Twilight', role:'HQ', pts:140, isNew:true, wargear:['Spear of Starlight','Twilight Wraith','Phoenix Lord 4+','Veil of Twilight'] },
    { id:'el_shadow_spectres', stats:['12"','3+','3+','3','3','1','2','8','4+'], name:'Shadow Spectres', role:'Elites', pts:22, isNew:true, wargear:['Prism Rifle','Holofield 5+ Invulnerable','Compact Formation'] },
  ],
  dark_eldar: [
    { id:'de_court_archon', stats:['7"','3+','3+','3','3','1','2','8','4+'], name:'Court of the Archon', role:'Elites', pts:30, isNew:true, wargear:['Mixed Specialists','Lethal Companions','Sslyth/Ur-Ghul/Medusae/Lhamean'] },
  ],
  orks: [
    { id:'ork_mozrog', stats:['10"','2+','5+','7','8','10','5','8','4+'], name:'Mozrog Skragbad', role:'HQ', pts:185, isNew:true, wargear:["Skragbad's Klaw","Big Chompa's Jaws",'Ere We Go'] },
    { id:'ork_beast_boyz', stats:['6"','3+','5+','4','4','2','2','7','6+'], name:'Beast Snagga Boyz', role:'Troops', pts:11, isNew:true, wargear:['Choppa','Slugga','Anti-vehicle Instincts'] },
    { id:'ork_squighog', stats:['10"','3+','5+','5','5','3','4','7','4+'], name:'Squighog Boys', role:'Fast Attack', pts:35, isNew:true, wargear:['Squighog Jaws','Stikka','Born to Scrap'] },
    { id:'ork_nob_squig', stats:['10"','2+','5+','6','6','5','5','8','4+'], name:'Nob on Smasha Squig', role:'HQ', pts:90, isNew:true, wargear:['Smasha Squig Jaws','Power Klaw','4+ Invulnerable'] },
    { id:'ork_beastboss', stats:['6"','2+','4+','5','5','5','5','9','4+'], name:'Beastboss', role:'HQ', pts:95, isNew:true, wargear:['Beastchoppa','Thump Gun','4+ Invulnerable','Beast Snagga Aura'] },
    { id:'ork_beastboss_squig', stats:['10"','2+','5+','6','7','8','5','9','4+'], name:'Beastboss on Squigosaur', role:'HQ', pts:160, isNew:true, wargear:['Boss Klaw',"Squigosaur's Jaws",'4+ Invulnerable','Beasthide'] },
    { id:'ork_kill_rig', stats:['9"','3+','5+','8','9','18','4','8','3+'], name:'Kill Rig / Hunta Rig', role:'Heavy Support', pts:230, isNew:true, wargear:['Supa-Lobba','Squig Launcha','Snagga Klaw','Transport 12'] },
  ],
  tau: [
    { id:'tau_farstalkers', stats:['7"','3+','3+','4','3','1','2','7','5+'], name:'Kroot Farstalkers', role:'Elites', pts:13, isNew:true, wargear:['Kroot Rifle','Jagga-blade','Fieldcraft','Prey Markers'] },
    { id:'tau_lone_spear', stats:['8"','2+','2+','4','4','5','4','8','4+'], name:'Kroot Lone-Spear', role:'HQ', pts:80, isNew:true, wargear:['Farstalker Longshot','Ritual Blade','Lone Operative','Apex Hunter'] },
    { id:'tau_war_shaper', stats:['7"','2+','3+','4','3','4','4','8','4+'], name:'Kroot War Shaper', role:'HQ', pts:60, isNew:true, wargear:['War-blade','Kroot Rifle','Pack Leader','Swift Ambush'] },
  ],
  necrons: [
    { id:'nec_silent_king', stats:['10"','2+','2+','7','7','18','6','10','2+'], name:'The Silent King (Szarekh)', role:'Lord of War', pts:420, isNew:true, wargear:['Sceptre of Eternal Glory','Flaymr Cannons','Lokhust Escorts','4+ Invulnerable'] , min:1, max:1, abilities:["We Are Eternal: Roll D6 per lost wound each turn — on 5+ regain 1 (max 3/turn)", "Triarch's Command: NECRONS within 6' re-roll hit rolls of 1", "The Awakening: Once per battle — one Necrons Infantry within 9' immediately attempts Reanimation for all lost models", "Quantum Shielding: First attack that deals 3+ damage is reduced to 2", "Undying Will: 4+ invulnerable save", "Lokhust Escorts: 2 bodyguard models absorbed wounds before Szarekh"]},
    { id:'nec_skorpekh_lord', stats:['8"','2+','3+','6','6','6','5','10','3+'], name:'Skorpekh Lord', role:'HQ', pts:130, isNew:true, wargear:['Flensing Claw','Hyperphase Harvester','Destroyer Cult Aura'] },
    { id:'nec_illuminor', stats:['10"','3+','3+','5','5','6','3','10','3+'], name:'Illuminor Szeras', role:'HQ', pts:145, isNew:true, wargear:['Eldritch Lance','Mechatendrils','The Great Work'] },
    { id:'nec_void_dragon', stats:['10"','2+','2+','8','8','16','6','10','4+'], name:'The Void Dragon', role:'Lord of War', pts:350, isNew:true, wargear:['Talons of the Void Dragon','Ray of the Void','Cosmic Power','4+ Invulnerable'] , min:1, max:1, abilities:["Unshackled C'tan: 4+ invulnerable save — immune to psychic powers — ignore hit modifiers", "Cosmic Power: Once per battle round choose one of three powers — meteorite / falling stars / seismic assault", "Lord of the Machine Cult: Necrons Vehicles within 9' re-roll hit rolls of 1", "Enslaved Star God: Start of your turns — on 1 suffer 1 mortal wound on 5+ regain 1 wound"]},
    { id:'nec_skorpekh_dest', stats:['8"','3+','3+','5','5','3','3','10','3+'], name:'Skorpekh Destroyers', role:'Elites', pts:40, isNew:true, wargear:['Hyperphase Threshers','Relentless Advance','Frenzied Charge'] },
    { id:'nec_reanimator', stats:['8"','4+','4+','6','6','8','2','10','3+'], name:'Canoptek Reanimator', role:'Heavy Support', pts:100, isNew:true, wargear:['Atomiser Beam','Reanimation Beam','Reanimation Tendrils'] },
    { id:'nec_lokhust_heavy', stats:['8"','3+','3+','5','5','4','2','10','3+'], name:'Lokhust Heavy Destroyer', role:'Heavy Support', pts:65, isNew:true, wargear:['Gauss Destructor','Lethal Precision'] },
    { id:'nec_ophydian', stats:['10"','3+','3+','5','5','3','4','10','3+'], name:'Ophydian Destroyers', role:'Elites', pts:42, isNew:true, wargear:['Hyperphase Reap-blades','Atomiser Beam','Burrowing Assault'] },
    { id:'nec_chronomancer', stats:['7"','3+','3+','4','4','4','3','10','3+'], name:'Canoptek Chronomancer', role:'HQ', pts:90, isNew:true, wargear:['Aeonstave','Entropic Lance','Temporal Displacement','Chronometron'] },
    { id:'nec_psychomancer', stats:['7"','3+','3+','4','4','4','3','10','3+'], name:'Psychomancer', role:'HQ', pts:80, isNew:true, wargear:['Abyssal Lance','Frightener','Writhing Worldscape'] },
    { id:'nec_convergence', stats:['-','-','-','-','7','4','-','-','3+'], name:'Convergence of Dominion', role:'Fortification', pts:70, isNew:true, wargear:['Starstele Network x3','Transdimensional Recall'] },
  ],
  tyranids: [
    { id:'ty_neurotyrant', stats:['6"','3+','3+','4','4','6','3','10','4+'], name:'Neurotyrant', role:'HQ', pts:130, isNew:true, wargear:['Psychic Scream','Neurotyrant Claws','Psychic Resonance','Mastery Level 2'] , min:1, max:1, abilities:["Synapse: Friendly Tyranids within 12' auto-pass Morale", "Shadow in the Warp: Enemy Psykers within 18' subtract 1 from Psychic tests", "Psychic Resonance: Friendly Psykers within 9' +1 to Psychic tests", "Neural Imperative: Once per turn — one friendly Tyranids within 12' may make a free Advance", "Neurogaunt Escorts: 2 escort models absorb wounds before Neurotyrant", "Psychic Fortress (WC5): Friendly Synapse within 12' cannot be targeted by psychic powers until next turn"]},
    { id:'ty_von_ryan', stats:['10"','3+','4+','4','4','2','4','8','4+'], name:"Von Ryan's Leapers", role:'Fast Attack', pts:30, isNew:true, wargear:['Leaper Talons','Prehensile Tail','Death Pounce','Skulker'] },
    { id:'ty_winged_prime', stats:['12"','2+','3+','5','4','5','4','10','3+'], name:'Winged Tyranid Prime', role:'HQ', pts:95, isNew:true, wargear:['Scything Talons','Devourer','Alpha Predator','5+ Invulnerable'] },
    { id:'ty_screamer_killer', stats:['8"','3+','5+','7','7','10','4','7','3+'], name:'Screamer-Killer', role:'Heavy Support', pts:140, isNew:true, wargear:['Clawed Forelimbs','Bio-plasmic Scream','Feeder Tendrils','Frenzied Charge'] },
    { id:'ty_barbgaunts', stats:['5"','4+','4+','3','3','1','1','7','6+'], name:'Barbgaunts', role:'Troops', pts:9, isNew:true, wargear:['Barblauncher','Symbiotic Targeting'] },
    { id:'ty_norn_emissary', stats:['8"','2+','2+','8','9','14','6','10','2+'], name:'Norn Emissary', role:'Lord of War', pts:290, isNew:true, wargear:['Massive Rending Claws','Psychic Lance','Synaptic Nexus','4+ Invulnerable'] , min:1, max:1, abilities:["Synaptic Nexus: ALL friendly Tyranids on the battlefield are within Synapse range", "Shadow in the Warp: Extended to 18'", "Psychic Aegis: 4+ invulnerable save — immune to non-Tyranid psychic powers", "Impervious Hide: Reduce all damage from attacks by 1 (minimum 1)", "Hive Mind's Will (WC8): One friendly unit may immediately shoot AND fight as bonus actions"]},
    { id:'ty_norn_assimilator', stats:['7"','3+','2+','8','9','14','4','9','2+'], name:'Norn Assimilator', role:'Lord of War', pts:270, isNew:true, wargear:['Bio-cannon','Rending Claws','Spine Banks','Impervious Hide'] },
    { id:'ty_deathleaper', stats:['10"','2+','3+','5','4','6','6','10','3+'], name:'Deathleaper', role:'HQ', pts:85, isNew:true, wargear:['Rending Claws','Flesh Hooks','Lone Operative','Chameleonic Skin'] },
    { id:'ty_neurolictor', stats:['9"','3+','3+','5','4','5','5','10','4+'], name:'Neurolictor', role:'Elites', pts:75, isNew:true, wargear:['Rending Claws','Neuroshock','Synapse','Lone Operative'] },
    { id:'ty_psychophage', stats:['9"','3+','4+','6','7','10','5','9','4+'], name:'Psychophage', role:'Heavy Support', pts:135, isNew:true, wargear:['Psychic Devourment','Talons and Claws','Psychic Hunger'] },
    { id:'ty_parasite', stats:['12"','2+','4+','5','4','5','5','9','4+'], name:'Parasite of Mortrex', role:'Elites', pts:65, isNew:true, wargear:['Claws and Stinger','Implant Attack','Lone Operative','5+ Invulnerable'] },
  ],
  genestealer_cults: [
    { id:'gc_reductus', stats:['7"','3+','3+','3','3','4','3','7','5+'], name:'Reductus Saboteur', role:'HQ', pts:55, isNew:true, wargear:['Blasting Charges','Remote Detonator','Cult Knife','Infiltrate'] },
    { id:'gc_benefictus', stats:['6"','3+','3+','3','3','4','3','8','5+'], name:'Benefictus', role:'HQ', pts:90, isNew:true, wargear:['Psionic Blast','Writhing Tendrils','Psychic Familiar','Neural Flare'] },
  ],
  adeptus_custodes: [
    { id:'ac_valoris', stats:['6"','2+','2+','5','5','7','6','10','2+'], name:'Trajann Valoris (updated)', role:'HQ', pts:175, isNew:true, wargear:["Watcher's Axe",'Balistus Grenade Launcher','4+ Invulnerable',"Captain-General Aura"] },
    { id:'ac_allarus', stats:['5"','2+','2+','5','5','3','4','9','2+'], name:'Allarus Custodians', role:'Elites', pts:65, isNew:true, wargear:['Castellan Axe','Balistus Grenade Launcher','4+ Invulnerable','Teleport Strike'] },
    { id:'ac_vertus_new', stats:['14"','2+','2+','5','5','3','4','9','2+'], name:'Vertus Praetors (updated)', role:'Fast Attack', pts:60, isNew:true, wargear:['Interceptor Lance','Salvo Launcher','4+ Invulnerable','Sweeping Advance'] },
    { id:'ac_wardens', stats:['6"','2+','2+','5','5','3','4','10','2+'], name:'Custodian Wardens', role:'Troops', pts:55, isNew:true, wargear:['Castellan Axe','Warden Halberd','4+ Invulnerable','Bulwark of Humanity'] },
    { id:'ac_achillus', stats:['8"','2+','2+','8','10','14','5','10','2+'], name:'Achillus Dreadnought', role:'Elites', pts:195, isNew:true, wargear:['Dreadspear','Twin Adrathic Destructor','4+ Invulnerable'] },
    { id:'ac_caladius', stats:['14"','4+','2+','8','9','12','3','9','2+'], name:'Caladius Grav-Tank', role:'Heavy Support', pts:185, isNew:true, wargear:['Twin Adrathic Destructor','Twin Lastrum Bolt Cannon','4+ Invulnerable','Hard to Hit'] },
  ],
  astra_militarum: [
    { id:'ag_lord_solar', stats:['12"','3+','2+','4','4','6','4','10','3+'], name:'Lord Solar Leontus', role:'HQ', pts:125, isNew:true, wargear:["Sol's Righteous Gaze",'Conquest','Grand Strategist','4+ Invulnerable'] },
    { id:'ag_ursula_creed', stats:['6"','4+','3+','3','3','4','3','9','5+'], name:'Ursula Creed', role:'HQ', pts:75, isNew:true, wargear:['Plasma Pistol','Power Sword','Voice of Command','Tactical Genius'] },
    { id:'ag_rogal_dorn', stats:['10"','5+','3+','8','11','18','3','9','2+'], name:'Rogal Dorn Battle Tank', role:'Heavy Support', pts:310, isNew:true, wargear:['Oppressor Cannon','Co-axial Multi-melta','2x Castigator Gatling Cannons'] },
    { id:'ag_kasrkin', stats:['6"','3+','3+','3','3','1','2','8','4+'], name:'Kasrkin', role:'Elites', pts:14, isNew:true, wargear:['Hot-shot Lasgun','Hot-shot Laspistol','Elite Soldiers','Grav-chute Insertion'] },
  ],
  adeptus_mechanicus: [
    { id:'am_serberys_raiders', stats:['14"','3+','3+','3','4','2','3','7','4+'], name:'Serberys Raiders', role:'Fast Attack', pts:28, isNew:true, wargear:['Cavalry Sabre','Archeo-revolver','Scouts','Hard to Hit'] },
    { id:'am_sulphurhounds', stats:['14"','3+','3+','3','4','2','3','7','4+'], name:'Serberys Sulphurhounds', role:'Fast Attack', pts:30, isNew:true, wargear:['Phosphor Pistols','Clawed Limbs','Bounding Advance'] },
    { id:'am_pteraxii_stery', stats:['12"','3+','3+','3','3','2','3','7','4+'], name:'Pteraxii Sterylizors', role:'Fast Attack', pts:26, isNew:true, wargear:['Phosphor Torch','Taser Goad','Inferno Descent'] },
    { id:'am_pteraxii_sky', stats:['12"','3+','3+','3','3','2','2','7','4+'], name:'Pteraxii Skystalkers', role:'Fast Attack', pts:22, isNew:true, wargear:['Pteraxii Flechette Carbine','Scintillating Blade','Aerial Drop'] },
    { id:'am_arch_strat', stats:['20-60"','6+','3+','6','7','10','2','8','4+'], name:'Archaeopter Stratagemini', role:'Flyer', pts:130, isNew:true, wargear:['Command Uplink','2x Cognis Heavy Stubbers','Stratagem Uplink'] },
    { id:'am_arch_trans', stats:['20-60"','6+','3+','6','7','10','2','8','4+'], name:'Archaeopter Transvector', role:'Flyer', pts:125, isNew:true, wargear:['2x Cognis Heavy Stubbers','Transport 10','Blistering Advance'] },
    { id:'am_arch_fusilave', stats:['20-60"','6+','3+','6','7','10','2','8','4+'], name:'Archaeopter Fusilave', role:'Flyer', pts:135, isNew:true, wargear:['Bomb Rack','2x Cognis Heavy Stubbers','Strafing Run'] },
    { id:'am_skorpius_dune', stats:['12"','5+','3+','6','8','11','3','8','3+'], name:'Skorpius Dunerider', role:'Dedicated Transport', pts:95, isNew:true, wargear:['Twin Cognis Heavy Stubber','Transport 11','Drifting Advance'] },
    { id:'am_skorpius_dis', stats:['12"','5+','3+','6','8','11','3','8','3+'], name:'Skorpius Disintegrator', role:'Heavy Support', pts:130, isNew:true, wargear:['Belleros Energy Cannon','Ferrumite Cannon','3x Cognis Stubbers'] },
  ],
  sisters_of_battle: [
    { id:'sob_morvenn_vahl', stats:['6"','2+','2+','5','6','8','6','10','2+'], name:'Morvenn Vahl', role:'HQ', pts:180, isNew:true, wargear:['Lance of Illumination','Purgator Missile Launcher','Paragon Fist','4+ Invulnerable'] },
    { id:'sob_palatine', stats:['6"','2+','2+','3','3','4','4','9','3+'], name:'Palatine', role:'HQ', pts:65, isNew:true, wargear:['Bolt Pistol','Power Sword','Blazing Radiance','Spiritual Leader'] },
    { id:'sob_dogmata', stats:['6"','3+','3+','3','3','4','3','9','3+'], name:'Dogmata', role:'HQ', pts:70, isNew:true, wargear:['Mace of the Righteous','Condemnor Boltgun','Verse of Holy War'] },
    { id:'sob_sacresants', stats:['6"','2+','3+','3','3','2','3','8','3+'], name:'Celestian Sacresants', role:'Elites', pts:18, isNew:true, wargear:['Anointed Halberd','Sacresant Shield 5+ Inv','Bodyguard'] },
    { id:'sob_paragon', stats:['8"','3+','3+','5','6','4','4','8','2+'], name:'Paragon Warsuits', role:'Heavy Support', pts:55, isNew:true, wargear:['Multi-melta / Heavy Bolter','Paragon War Blade','Righteous Charge'] },
    { id:'sob_castigator', stats:['10"','4+','3+','6','9','12','3','8','3+'], name:'Castigator', role:'Heavy Support', pts:160, isNew:true, wargear:['Castigator Battle Cannon','2x Hurricane Bolters','Shield of Faith'] },
  ],
  imperial_knights: [
    { id:'ik_war_dog_stalker', stats:['10"','3+','3+','6','9','12','3','8','3+'], name:'War Dog Stalker', role:'Heavy Support', pts:145, isNew:true, wargear:['Reaper Chaintalon','Stormspear Rocket Pod','Ion Shield 5+'] },
    { id:'ik_war_dog_karnivore', stats:['10"','2+','4+','6','9','12','4','8','3+'], name:'War Dog Karnivore', role:'Heavy Support', pts:135, isNew:true, wargear:['Paired Reaper Chaintalons','Ion Shield 5+','Hunter Instincts'] },
    { id:'ik_war_dog_brigand', stats:['10"','3+','3+','6','9','12','3','8','3+'], name:'War Dog Brigand', role:'Heavy Support', pts:155, isNew:true, wargear:['Avenger Gatling Cannon','Thermal Spear','Ion Shield 5+'] },
    { id:'ik_canis_rex_new', stats:['12"','3+','3+','8','12','24','4','9','3+'], name:'Canis Rex (updated)', role:'Lord of War', pts:430, isNew:true, wargear:['Reaper Chainsword','Thermal Cannon','Ironstorm Missile Pod','Ion Shield 4+'] },
  ],
  // ---- NAMED CHARACTERS ----
  space_marines_named: [
    { id:"sm_guilliman", name:"Roboute Guilliman", stats:["6\"","2+","2+","6","6","9","5","10","2+"], role:"Lord of War", pts:360, isNew:true,
      wargear:["Hand of Dominion","Emperor's Sword","Armour of Fate"], min:1, max:1, ppm:0,
      abilities:["Spiritual Rites: Re-roll all failed hit and wound rolls for friendly Ultramarines units within 6\"",
                 "Adept of the Codex: +1 CP each battle round","4+ invulnerable save",
                 "Regenerate: Roll D6 at start of each turn — on 4+ regain D3 lost wounds","Ultramarines only"] },
    { id:"sm_calgar", name:"Marneus Calgar", stats:["6\"","2+","2+","5","5","7","5","10","2+"], role:"HQ", pts:220, isNew:true,
      wargear:["Gauntlets of Ultramar","Artificer Armour"], min:1, max:1, ppm:0,
      abilities:["Chapter Master: Re-roll all failed hit rolls for friendly Ultramarines units within 6\"",
                 "God of War: Once per battle round use a Stratagem for 0 CP","4+ invulnerable save","Ultramarines only"] },
    { id:"sm_shrike", name:"Kayvaan Shrike", stats:["12\"","2+","2+","4","4","5","6","9","3+"], role:"HQ", pts:110, isNew:true,
      wargear:["Blackshroud","Master-crafted Bolter","Jump Pack"], min:1, max:1, ppm:0,
      abilities:["Master of Shadows: This model and friendly units within 3\" always count as in cover",
                 "Strike from the Shadows: May deploy anywhere more than 9\" from enemy at end of first Movement phase",
                 "Raven Guard only"] },
    { id:"sm_kantor", name:"Pedro Kantor", stats:["6\"","2+","2+","4","4","5","5","10","2+"], role:"HQ", pts:130, isNew:true,
      wargear:["Dorn's Arrow","Duty's Burden"], min:1, max:1, ppm:0,
      abilities:["Inspiring Presence: Friendly Crimson Fists within 6\" gain +1 Attack",
                 "Hold the Line: Friendly units within 12\" auto-pass Morale","4+ invulnerable save","Crimson Fists only"] },
    { id:"sm_lysander", name:"Lysander", stats:["5\"","2+","3+","5","5","6","4","9","2+"], role:"HQ", pts:175, isNew:true,
      wargear:["The Fist of Dorn","Storm Shield"], min:1, max:1, ppm:0,
      abilities:["Inspiring Presence","3+ invulnerable save from Storm Shield",
                 "Eternal Warrior: Reduce all damage dealt to this model by 1 (min 1)","Imperial Fists only"] },
    { id:"sm_khan", name:"Kor'sarro Khan", stats:["14\"","2+","2+","4","4","5","5","9","3+"], role:"HQ", pts:120, isNew:true,
      wargear:["Moonfang","Bolt Pistol","Jetbike"], min:1, max:1, ppm:0,
      abilities:["Drawn in for the Kill: Re-roll failed charge rolls for friendly White Scars within 6\"",
                 "Turbo-boost: May Advance and charge in same turn","White Scars only"] },
  ],
  astra_militarum_named: [
    { id:"ag_yarrick", name:"Commissar Yarrick", stats:["6\"","3+","3+","4","3","5","3","10","4+"], role:"HQ", pts:100, isNew:true,
      wargear:["Bale Eye","Power Klaw","Storm Bolter","Iron Will"], min:1, max:1, ppm:0,
      abilities:["Inspiring Presence: Friendly Astra Militarum units within 6\" auto-pass Morale",
                 "Bale Eye: At start of Fight phase deal 1 mortal wound to one enemy model within 1\"",
                 "Iron Will: The first time Yarrick is slain roll D6 — on 2+ he survives with 1 wound",
                 "Voice of Command: Issue 2 orders per turn"] },
    { id:"ag_creed", name:"Ursarkar E. Creed", stats:["6\"","3+","3+","3","3","4","3","10","5+"], role:"HQ", pts:95, isNew:true,
      wargear:["Bolt Pistol","Power Sword"], min:1, max:1, ppm:0,
      abilities:["Voice of Command: Issue 2 orders per turn to units within 12\"",
                 "Warlord of Cadia: Once per battle — one friendly unit within 18\" may shoot or fight as bonus action",
                 "Tactical Genius: Re-roll any single hit/wound/save die once per phase","Cadian only"] },
    { id:"ag_pask", name:"Tank Commander Pask", stats:["10\"","5+","2+","6","8","12","3","9","3+"], role:"HQ", pts:183, isNew:true,
      wargear:["Leman Russ Battle Cannon","Heavy Bolter","Lascannon Sponsons"], min:1, max:1, ppm:0,
      abilities:["Master of Armour: Friendly Astra Militarum Vehicles within 6\" re-roll hit rolls of 1",
                 "Grinding Advance","Smoke Launchers",
                 "Knight Commander: Counts as issuing one order to himself each turn automatically"] },
  ],
  orks_named: [
    { id:"ork_ghazghkull", name:"Ghazghkull Thraka", stats:["10\"","2+","3+","8","9","12","6","9","2+"], role:"Lord of War", pts:300, isNew:true,
      wargear:["Gork's Klaw","Mork's Roar","Da Iron Skin"], min:1, max:1, ppm:0,
      abilities:["Prophet of the Waaagh!: Once per battle — all friendly Orks may Advance and charge this turn",
                 "Blessed by the Gods: 4+ invulnerable save — on 6 restore 1 wound instead of taking it",
                 "The Voice of Gork and Mork: Friendly Orks within 12\" auto-pass Morale",
                 "Ere We Go: Re-roll failed charge rolls for all friendly Orks",
                 "Unstoppable: When this model loses its last wound roll D6 — on 2+ it survives with D3 wounds"] },
    { id:"ork_makari", name:"Makari (Ghazghkull's Grot)", stats:["5\"","4+","4+","2","2","1","1","7","6+"], role:"HQ", pts:30, isNew:true,
      wargear:["Lucky Stick"], min:1, max:1, ppm:0,
      abilities:["Lucky Banner: Ghazghkull gains a 3+ invulnerable save while Makari is within 3\"",
                 "Must be taken alongside Ghazghkull","Surprisingly Killy: +1 Attack if charged"] },
    { id:"ork_gazrot", name:"Gazrot Goresnappa", stats:["5\"","2+","4+","6","6","7","5","9","2+"], role:"HQ", pts:135, isNew:true,
      wargear:["Da Biggest Klaw","Shoota"], min:1, max:1, ppm:0,
      abilities:["Ere We Go","Waaagh Leader: Friendly Orks within 8\" re-roll hit rolls of 1",
                 "Da Biggest Klaw: Wound rolls of 6 deal D3 additional mortal wounds","4+ invulnerable save"] },
    { id:"ork_zagstruk", name:"Zagstruk", stats:["12\"","2+","3+","5","5","5","5","9","4+"], role:"HQ", pts:90, isNew:true,
      wargear:["Da Vulcha's Klaws","Slugga","Jump Pack"], min:1, max:1, ppm:0,
      abilities:["Ere We Go","Vulcha Squad Leader: May be deployed with a unit of Stormboyz — acts as their boss",
                 "Da Drop: When arriving from deep strike add 2 to charge rolls this turn","4+ invulnerable save"] },
  ],
  space_wolves_named: [
    { id:"sw_bjorn", name:"Bjorn the Fell-Handed", stats:["6\"","2+","3+","7","7","12","5","9","2+"], role:"Elites", pts:200, isNew:true,
      wargear:["Trueclaw","Helfrost Cannon or Twin Lascannon"], min:1, max:1, ppm:0,
      abilities:["The Oldest and the Deadliest: Friendly Space Wolves within 6\" re-roll hit rolls of 1",
                 "Ancient: Hero of the Chapter — once per game may use any Stratagem for 0 CP",
                 "Explodes: On 6 when destroyed — D6 mortal wounds within 3\"","Space Wolves only"] },
    { id:"sw_canis", name:"Canis Wolfborn", stats:["12\"","3+","3+","5","5","5","5","8","3+"], role:"HQ", pts:95, isNew:true,
      wargear:["Fangsword","Fang of Morkai"], min:1, max:1, ppm:0,
      abilities:["Bestial Nature: +1 Attack for each Fenrisian Wolf within 6\"",
                 "Ride the Wolves: Always counts as having made a charge move if within 1\" of enemy at start of Fight phase",
                 "Space Wolves only"] },
  ],
  blood_angels_named: [
    { id:"ba_tycho", name:"Brother-Captain Tycho", stats:["6\"","2+","2+","4","4","5","5","9","2+"], role:"HQ", pts:95, isNew:true,
      wargear:["Master-crafted Bolter","Combi-melta","The Blood Song"], min:1, max:1, ppm:0,
      abilities:["Death Mask of Sanguinius: Enemy units within 3\" subtract 1 from Leadership",
                 "Honour of the Chapter: Friendly Blood Angels within 6\" re-roll hit rolls of 1",
                 "4+ invulnerable save","Blood Angels only"] },
  ],
  tyranids_named: [
    { id:"ty_swarmlord", name:"The Swarmlord", stats:["10\"","2+","3+","8","8","12","5","10","3+"], role:"HQ", pts:250, isNew:true,
      wargear:["Bone Sabres x4","Psychic Scream"], min:1, max:1, ppm:0,
      abilities:["Hive Commander: Two friendly Tyranid units within 6\" may re-roll failed charge rolls",
                 "Synaptic Lynchpin: Synapse range extended to 24\"","Shadow in the Warp",
                 "5+ invulnerable save","Psyker: Mastery Level 3",
                 "Alien Cunning: Once per battle at start of any phase — move up to 12\" ignoring terrain"] },
    { id:"ty_old_one_eye", name:"Old One Eye", stats:["7\"","3+","4+","9","8","10","5","7","3+"], role:"Heavy Support", pts:170, isNew:true,
      wargear:["Massive Scything Talons","Crushing Claws","Bio-plasma"], min:1, max:1, ppm:0,
      abilities:["Regeneration: Roll D6 at start of each turn — on 4+ restore D3 lost wounds",
                 "Living Battering Ram: Add D3 to Attacks on turn it charges","Instinctive Behaviour",
                 "Inspiring Presence: Friendly Carnifexes within 6\" re-roll hit rolls of 1"] },
  ],
  necrons_named: [
    { id:"nec_trazyn", name:"Trazyn the Infinite", stats:["5\"","3+","3+","5","5","5","3","10","3+"], role:"HQ", pts:130, isNew:true,
      wargear:["Empathic Obliterator"], min:1, max:1, ppm:0,
      abilities:["Prismatic Gallery: Once per battle — choose one of several powerful one-off abilities",
                 "Surrogate Hosts: When slain roll D6 — on 2+ replace with a friendly Lychguard or Immortal within 3\"",
                 "Reanimation Protocols","Living Metal"] },
    { id:"nec_anrakyr", name:"Anrakyr the Traveller", stats:["5\"","3+","3+","5","5","5","3","10","3+"], role:"HQ", pts:130, isNew:true,
      wargear:["Tachyon Arrow","Warscythe"], min:1, max:1, ppm:0,
      abilities:["Pyrrhian Eternals: Once per battle — one friendly Necrons unit within 6\" may be activated twice this phase",
                 "Lord of the Pyrrhian Legions: Friendly Necrons within 6\" re-roll hit rolls of 1",
                 "Reanimation Protocols","Mind in the Machine: May attempt to take control of an enemy Vehicle within 12\""] },
  ],
  chaos_space_marines_named: [
    { id:"csm_abaddon", name:"Abaddon the Despoiler", stats:["6\"","2+","2+","5","5","8","5","10","2+"], role:"Lord of War", pts:285, isNew:true,
      wargear:["Drach'nyen","Talon of Horus","Black Plate"], min:1, max:1, ppm:0,
      abilities:["Warmaster: Friendly Chaos Space Marines within 6\" re-roll all failed hit rolls",
                 "Four-Armed Terror: Once per Fight phase make 2 additional attacks with the Talon of Horus",
                 "Black Crusader: Ignore Morale for all friendly Chaos units within 6\"","4+ invulnerable save",
                 "Marks of All Chaos: Counts as bearing all four Marks simultaneously"] },
    { id:"csm_huron", name:"Huron Blackheart", stats:["6\"","2+","2+","4","4","5","4","9","3+"], role:"HQ", pts:115, isNew:true,
      wargear:["The Tyrant's Claw","Blackheart's Spitespitter","The Hamadrya"], min:1, max:1, ppm:0,
      abilities:["Psyker: Mastery Level 1","Master of the Renegades: Friendly Chaos units within 6\" re-roll hit rolls of 1",
                 "A Bitter Taste of Victory: Restore 1 wound each time a model is slain within 6\"",
                 "4+ invulnerable save"] },
    { id:"csm_typhus", name:"Typhus — Herald of Nurgle", stats:["5\"","3+","3+","5","5","7","4","9","3+"], role:"HQ", pts:175, isNew:true,
      wargear:["Manreaper","Plague Sprayer"], min:1, max:1, ppm:0,
      abilities:["Psyker: Mastery Level 2",
                 "Host of the Destroyer Hive: Friendly Poxwalkers within 7\" add 1 to their Attacks",
                 "Destroyer Hive: At start of each Fight phase deal D3 mortal wounds to one enemy unit within 1\"",
                 "Disgustingly Resilient: Roll D6 each wound — on 5+ ignore it",
                 "4+ invulnerable save","Death Guard only"] },
    { id:"csm_ahriman_foot", name:"Ahriman on Foot", stats:["6\"","3+","3+","4","4","5","3","9","3+"], role:"HQ", pts:165, isNew:true,
      wargear:["Black Staff of Ahriman","Inferno Bolt Pistol"], min:1, max:1, ppm:0,
      abilities:["Psyker: Mastery Level 3","Vessel of Chaos: Re-roll all Psychic tests",
                 "Ether Walk: Once per turn — teleport up to 18\" instead of moving normally",
                 "4+ invulnerable save","Thousand Sons only"] },
  ],
  eldar_named: [
    { id:"el_eldrad", name:"Eldrad Ulthran", stats:["7\"","3+","2+","3","3","5","2","9","6+"], role:"HQ", pts:130, isNew:true,
      wargear:["Staff of Ulthamar","Shuriken Pistol"], min:1, max:1, ppm:0,
      abilities:["Psyker: Mastery Level 4 — knows Smite + 4 powers from Runes of Battle and Runes of Fate",
                 "Fate's Messenger: Once per turn — after manifesting a power choose one: restore 1 lost wound OR revert one failed die roll",
                 "Guide + Doom + Fortune + Will of Asuryan included in known powers",
                 "Ancient Doom","Ulthwe only (or any Craftworlds)"] },
    { id:"el_asurmen", name:"Asurmen — Hand of Asuryan", stats:["7\"","2+","2+","3","3","6","5","9","2+"], role:"HQ", pts:180, isNew:true,
      wargear:["Sword of Asur (x2)","Shuriken Pistol"], min:1, max:1, ppm:0,
      abilities:["Phoenix Lord: 4+ invulnerable save",
                 "Lord of All Dire Avenger Shrines: Friendly Dire Avengers within 6\" re-roll all failed hit rolls",
                 "Hand of Asuryan: Enemies that charged this unit must re-roll successful hit rolls in subsequent Fight phase"] },
    { id:"el_yriel", name:"Prince Yriel", stats:["7\"","2+","2+","4","3","5","6","9","3+"], role:"HQ", pts:100, isNew:true,
      wargear:["Spear of Twilight","Eye of Wrath"], min:1, max:1, ppm:0,
      abilities:["Fleet of Foot: May Advance and still charge",
                 "Spear of Twilight: Wound rolls of 6 deal D3 mortal wounds in addition",
                 "Eye of Wrath: Once per game — deal D3 mortal wounds to all enemies within 3\"",
                 "Doomed: At end of each battle round roll D6 — on 1 Yriel loses 1 wound"] },
    { id:"el_jain_zar", name:"Jain Zar — Storm of Silence", stats:["8\"","2+","2+","3","3","5","6","9","4+"], role:"HQ", pts:140, isNew:true,
      wargear:["Zhai Morenn","Silent Death","Banshee Mask"], min:1, max:1, ppm:0,
      abilities:["Phoenix Lord: 4+ invulnerable save",
                 "Lord of All Howling Banshee Shrines: Friendly Howling Banshees within 6\" always fight first",
                 "Banshee Mask: Enemy units charged by Jain Zar cannot fire Overwatch",
                 "Swift Strikes: Always fights first regardless of any other rule"] },
    { id:"el_karandras", name:"Karandras — The Shadow Hunter", stats:["7\"","2+","2+","4","3","5","5","9","3+"], role:"HQ", pts:165, isNew:true,
      wargear:["Scorpion's Claw","Mandiblasters","Scorpion Chainsword"], min:1, max:1, ppm:0,
      abilities:["Phoenix Lord: 4+ invulnerable save",
                 "Lord of All Striking Scorpion Shrines: Friendly Striking Scorpions within 6\" re-roll hit rolls of 1 and count as in cover",
                 "Infiltrate: Deploy anywhere more than 9\" from enemy",
                 "Crack Shot: Re-roll failed wound rolls"] },
  ],
  dark_angels_named: [
    { id:"da_belial", name:"Belial — Master of the Deathwing", stats:["5\"","2+","2+","4","4","5","5","9","2+"], role:"HQ", pts:135, isNew:true,
      wargear:["Sword of Silence","Storm Bolter"], min:1, max:1, ppm:0,
      abilities:["Master of the Deathwing: Friendly Deathwing Terminators within 6\" re-roll all failed hit rolls",
                 "3+ invulnerable save: Tactical Aegis",
                 "Deathwing Assault: All Deathwing units may arrive from deep strike on turn 1 if Belial is on the battlefield",
                 "Dark Angels only"] },
    { id:"da_sammael", name:"Sammael — Master of the Ravenwing", stats:["16\"","2+","2+","4","4","5","5","9","3+"], role:"HQ", pts:185, isNew:true,
      wargear:["Raven Sword","Plasma Cannon","Corvus Hammer","Jetbike"], min:1, max:1, ppm:0,
      abilities:["Master of the Ravenwing: Friendly Ravenwing units within 9\" re-roll hit rolls of 1",
                 "4+ invulnerable save","Jink: 5+ invulnerable save if the model Advances",
                 "Hit and Run: Once per game — after fighting disengage 2D6\" ignoring terrain",
                 "Dark Angels only"] },
  ],
  adeptus_mechanicus_named: [
    { id:"am_cawl_named", name:"Belisarius Cawl", stats:["7\"","3+","3+","5","5","8","4","9","2+"], role:"HQ", pts:200, isNew:true,
      wargear:["Mechadendrites","Omnissian Axe","Cawl's Wrath"], min:1, max:1, ppm:0,
      abilities:["Lord of the Forge: Friendly Adeptus Mechanicus Vehicles within 6\" re-roll hit rolls of 1",
                 "Canticles of the Omnissiah: Cawl knows all Canticles — may pick freely rather than randomly",
                 "Repairing Mechadendrites: At end of each Movement phase restore D3 wounds to one friendly Vehicle within 3\"",
                 "Data Tether: Friendly Skitarii within 6\" add 1 to Leadership","5+ invulnerable save"] },
  ],
  sisters_of_battle_named: [
    { id:"sob_celestine_nc", name:"Saint Celestine", stats:["12\"","2+","2+","3","3","5","4","9","3+"], role:"HQ", pts:200, isNew:true,
      wargear:["The Ardent Blade","Plasma Pistol"], min:1, max:1, ppm:0,
      abilities:["Living Saint: 4+ invulnerable save — when first slain she is resurrected with D6 wounds on a 2+",
                 "Divine Intervention: Friendly Adepta Sororitas within 6\" re-roll hit rolls of 1",
                 "Acts of Faith","Geminae Superia: Two bodyguard models absorb wounds before Celestine"] },
    { id:"sob_ephrael", name:"Ephrael Stern", stats:["7\"","2+","2+","3","3","5","5","9","3+"], role:"HQ", pts:95, isNew:true,
      wargear:["The Ardent Blade","Plasma Pistol"], min:1, max:1, ppm:0,
      abilities:["Psyker: Mastery Level 1",
                 "The Heretic's Bane: Wound rolls of 6 against enemy Characters deal D3 mortal wounds",
                 "4+ invulnerable save","Acts of Faith",
                 "Daemonbane: Re-roll all failed wound rolls against Chaos and Daemon units"] },
  ],
  genestealer_cults_named: [
    { id:"gc_pureblood", name:"Pureblood Genestealer", stats:["8\"","2+","3+","5","4","3","4","9","5+"], role:"Elites", pts:50, isNew:true,
      wargear:["Rending Claws","Scything Talons"], min:1, max:1, ppm:0,
      abilities:["Hyper-reflexes: 5+ invulnerable save",
                 "Alpha: Friendly Genestealers within 6\" re-roll hit rolls of 1",
                 "Locus of the Four-Armed Emperor: Once per Fight phase one friendly Genestealer unit within 6\" may immediately fight as bonus action"] },
  ],
  chaos_daemons_named: [
    { id:"cd_skarbrand", name:"Skarbrand the Exiled", stats:["8\"","2+","5+","8","8","14","8","10","4+"], role:"Lord of War", pts:300, isNew:true,
      wargear:["Slaughter","Carnage"], min:1, max:1, ppm:0,
      abilities:["Roar of Total Rage: All enemy units within 8\" subtract 2 from Leadership",
                 "Daemonic: 4+ invulnerable save",
                 "Total Carnage: Attacks increase by 1 for each wound lost (max +4)",
                 "Hatred Incarnate: Cannot use psychic powers — only charges and fights"] },
    { id:"cd_epidemius", name:"Epidemius — Tallyman of Nurgle", stats:["5\"","4+","4+","3","4","4","2","9","5+"], role:"HQ", pts:95, isNew:true,
      wargear:["Balesword","Nurgling Bodyguard"], min:1, max:1, ppm:0,
      abilities:["Disgustingly Resilient","Tally of Pestilence: Track kills — at milestone thresholds gain army-wide buffs",
                 "Daemon of Nurgle: 5+ invulnerable save",
                 "Tally Bonuses: At 7/14/21/28 kills gain buffs to Toughness / Wound recovery / AP / mortal wounds"] },
  ],
};

